### ISSUE TITLE
'singInWithPhoneNumber' method not found 

### ISSUE THREAD

**Issue by thandilexyz** [FirebaseExtended/firebase-dart#260]
Hi,

The **signInWithPhoneNumber** method is not available, here is my code below. Is a there another alternative ?

```
FirebaseAuth.instance.signInWithPhoneNumber (
      verificationId: verificationId,
      smsCode: smsCode)
```

I am using ------>  *Dart VM version: 2.5.2 on "Linux_x64"*

Version of the **firebase** package:
```
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
```
